### ISSUE TITLE
ExeSpy v1.0.0 does not run on Windows 10

### ISSUE THREAD

**Issue by aquila-XP** [andyjsmith/Exe-Spy#1]
I unpacked the archive `exespy_1.0.0_windows.zip` and tried to run `exespy.exe`.
On Windows 10 Enterprise 2015 LTSB x64 I get this **Dialog Box**:
`This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`
`Available platform plugins are: direct2d, minimal, offscreen, windows.`
I get the same error also when running `exespy_1.0.0_windows_portable.exe`.

**Comment by andyjsmith** [comment]
Please see the supported platforms for Qt 6, Windows 10 1809 or newer is required. Unfortunately I would rather keep the dependencies updated to support modern features compared to supporting EOL OS versions.
https://doc.qt.io/qt-6.5/supported-platforms.html
